### ISSUE TITLE
Port to react-query 4.x.x to support React 18

### ISSUE THREAD

**Issue by swouf** [graasp/graasp-apps-query-client#31]
It seems that react-query 3.x.x isn't compatible with React 18. Therefore, we should consider porting the apps-query-client to react-query 4.x.x in order to be able to port the apps to React 18.

**Comment by pyphilia** [comment]
I see react-query 4 is not out now. Could you link to some ref where it's mentioned that react-query3 doesn't work with react18?

**Comment by spaenleh** [comment]
It is mentioned [in this comment by the author of react-query](https://github.com/tannerlinsley/react-query/issues/3476#issuecomment-1092501739). 

TLDR: 
- in React 18, FunctionComponent doesn't have any relationship with PropsWithChildren
- react-query needs to update how they create the QueryClientProvider
- React 18 support will come in react-query v4.x.x but for the moment the version 4 is still in beta tough the author says that not much will change from the beta to the final release of v4.
